export const trendsData = [
    {
        id:'trend1',
        ubication:'Peru',
        hash:"tengohambre",
        tweets:5678
    },
    {
        id:'trend2',
        ubication:'Peru',
        hash:"awitadecoco",
        tweets:3458
    },
    {
        id:'trend3',
        ubication:'Colombia',
        hash:"tengohambre",
        tweets:89733
    },
]